### PR TITLE
Add Maven Dependency information

### PR DESCRIPTION
**Pull request by JamieSinn**

### CODE REVIEW

**Comment by JamieSinn** [comment]
@DarkBlade12

**Comment by DarkBlade12** [comment]
Don't you have to change the version to 1.7.0-SNAPSHOT? Since you told me to rename it.

**Comment by JamieSinn** [comment]
That's for the snapshot version. You'll update the maven version depending on whether you want the stable version, or if you want to have the latest version.

**Comment by DarkBlade12** [comment]
Ah ok, thanks for clarifying.

**Comment by JamieSinn** [comment]
And http://ci.sinndevelopment.com/job/ParticleEffect%20Library/8/ was triggered when you pushed the commit!

Magic!

**Comment by DarkBlade12** [comment]
Yep, i saw that^^

**Comment by DarkBlade12** [comment]
However how can you use ParticleEffect as a Maven dependency now? Since it's not a plugin the classes won't be loaded if the jar is just put into the plugin folder.

**Comment by JamieSinn** [comment]
Ah, you'll need to add a plugin called shade 
I'll get to my desktop in a second

**Comment by DarkBlade12** [comment]
So do I just have to add this plugin to the pom.xml like this:
```    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.4.1</version>
        <configuration>
          <!-- put your configurations here -->
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>```
What should I add in the configuration section then?

**Comment by JamieSinn** [comment]
```
<artifactSet>
                        <includes>
                            <include>com.darkblade12:*</include>
                        </includes>
                    </artifactSet>
```

**Pull request merged**
