### PR TITLE
Add maven support - as well as add it to a remote repo.

### PR DESCRIPTION
**Pull request by JamieSinn**
```   
<dependency>
            <groupId>com.darkblade12</groupId>
            <artifactId>particleeffect</artifactId>
            <version>1.7</version>
</dependency> 

<repository>
            <id>sinndev-repo</id>
            <url>http://repo.sinndev.com/content/groups/public/</url>
</repository>

```

Also put it up onto my jenkins server.
http://ci.sinndevelopment.com/job/ParticleEffect%20Library/

If merged, you will need to edit your webhooks/services to add Jenkins - (GitHub Plugin)
at the url: http://ci.sinndevelopment.com/github-webhook/

Documentation:

http://ci.sinndevelopment.com/job/ParticleEffect%20Library/ws/target/site/apidocs/index.html

### CODE REVIEW

**Comment by DarkBlade12** [comment]
Thanks for your addition and for hosting this on your repo! I'm going to pull these changes the following week.

**Comment by JamieSinn** [comment]
No problem, just make sure to change the version in the pom file before you commit, just changing it to a snapshot will do fine

**Comment by JamieSinn** [comment]
@darkblade12
I'd still like to pull this

**Comment by DarkBlade12** [comment]
Sorry for letting you wait so long, i was kinda busy and forgot about this. However i don't know exactly how to edit the webhooks/services since i'm pretty new to maven. Could you give me a more detailed explanation? (If I visit the link you posted and click "Try POSTing" it brings up an error)

**Comment by JamieSinn** [comment]
You need to set up the github side, in the Web hook and services area

**Comment by DarkBlade12** [comment]
I already added the Jenkins service with the url you provide and tested it with a small commit.

**Comment by JamieSinn** [comment]
Nope, I'll set it up on my end.
I'll comment here in a few to tell you when to test

**Comment by JamieSinn** [comment]
Okay, test it now

**Pull request merged**
